---
# This role is for configuring the jump host

- name: set up prereqs
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - nfs-common
    - nfs-kernel-server
    - htop

- name: copy certs
  copy:
    src: "{{ ssl_cert_dir }}/{{ item }}"
    dest: /etc/ssl/{{ item }}
    owner: www-data
    group: www-data
  with_items:
    - "*.qiime2.org.chained.crt"
    - "*.qiime2.org.key"

- name: set up nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default

- name: restart services
  service:
    name: nginx
    state: restarted

- name: create mount point
  file:
    path: /mnt/home
    state: directory
    mode: 0777
    owner: ubuntu
    group: ubuntu

- name: prep shared drive filesystem
  filesystem:
    fstype: ext4
    dev: /dev/xvdb

- name: mount ebs
  mount:
    name: /mnt/home
    src: /dev/xvdb
    fstype: auto
    state: mounted

- name: set up nfs server
  lineinfile:
    dest: /etc/exports
    insertafter: EOF
    line: "/mnt/home {{ vpc_cidr_block }}(rw,nohide,fsid=0,insecure,no_subtree_check,async)"

- name: set up /etc/skel/.bashrc
  lineinfile:
    dest: /etc/skel/.bashrc
    line: "{{ item }}"
  with_items:
    - export PATH="{{ miniconda_path }}/bin:$PATH"
    - export MPLBACKEND=agg
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - source activate qiime2-{{ qiime2_release }}
    - source tab-qiime
    - 'export PS1="working directory: \$PWD\n$ "'

- name: ensure skel ssh dir is present
  file:
    path: /etc/skel/.ssh
    state: directory

- name: add admin authorized keys
  copy:
    src: "{{ authorized_keys_dir }}/authorized_keys"
    dest: /etc/skel/.ssh/authorized_keys

- name: create workshop working dir
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items:
    - { path: '/etc/skel/workshop', state: 'directory' }

- name: create user accounts
  user:
    name: "{{ item.name }}"
    password: "{{ item.hash }}"
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    createhome: True
    home: "/mnt/home/{{ item.name }}"
  with_items: "{{ users }}"

- name: create admin accounts
  user:
    name: "{{ item }}"
    password: "$6$rounds=656000$odzDwS9gk.h9jRDb$DgPtdKpgV0qg.WP6d7Rz1Jc51GsGyiNhzjMmga/Nh5Gwwav/k5OUTk8ACcZTYSTOc//uZVzaCWilF9Mx2ImDi."
    shell: /bin/bash
    createhome: True
    home: "/home/{{ item }}"
  with_items:
    - admin1
    - admin2
    - admin3

- name: configure ssh for jumping
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item }}"
    block: |
      Match Group {{ hostvars[item]['grp'] }}
          ForceCommand ssh {{ item }}
  with_items: "{{ groups['compute_hosts'] }}"

- name: restart services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - ssh
    - nfs-kernel-server
    - nginx

- name: remove known_hosts
  file:
    path: "/mnt/home/{{ item.name }}/.ssh/known_hosts"
    state: absent
  with_items: "{{ users }}"

- name: shared data dir
  file:
    path: "/mnt/home/{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - shared
    - shared/qiime2-moving-pictures-tutorial
    - shared/qiime2-moving-pictures-tutorial/emp-single-end-sequences

- name: download data
  get_url:
    url: "{{ item.url }}"
    dest: "/mnt/home/shared/qiime2-moving-pictures-tutorial/{{ item.dest }}"
    mode: 0777
    force: False
    timeout: 60
  with_items:
    - { url: "https://data.qiime2.org/{{ qiime2_release }}/tutorials/moving-pictures/sample_metadata.tsv", dest: "sample-metadata.tsv" }
    - { url: "https://data.qiime2.org/{{ qiime2_release }}/tutorials/moving-pictures/emp-single-end-sequences/barcodes.fastq.gz", dest: "emp-single-end-sequences/barcodes.fastq.gz" }
    - { url: "https://data.qiime2.org/{{ qiime2_release }}/tutorials/moving-pictures/emp-single-end-sequences/sequences.fastq.gz", dest: "emp-single-end-sequences/sequences.fastq.gz" }
